package com.playhavior.model;

public enum PathwayCode {
    RESPECTFUL_COMMUNICATION,
    INCLUSION_AND_ANTI_DISCRIMINATION,
    THREAT_DEESCALATION,
    SAFE_RESPONSE_TO_SELF_HARM_LANGUAGE,
    CONSENT_AND_SEXUAL_BOUNDARIES,
    PRIVACY_AND_PERSONAL_INFORMATION,
    HONEST_IDENTITY_AND_COMMUNICATION,
    RESPONSIBLE_COMMUNICATION_USE,
    DIGITAL_SCAM_AND_ACCOUNT_SAFETY,
    FAIR_PLAY_AND_GAME_INTEGRITY,
    SAFETY_AND_LEGAL_BOUNDARIES,
    ACCOUNT_AND_PLATFORM_RESPONSIBILITY,
    RESPONSIBLE_CONTENT_SHARING,
    COMMUNITY_STANDARDS_FOUNDATION
}
