package com.playhavior.model;

public enum ViolationCategory {
    HARASSMENT_BULLYING,
    HATE_DISCRIMINATION,
    THREATS_VIOLENT_INTIMIDATION,
    SELF_HARM_SUICIDE_ENCOURAGEMENT,
    SEXUAL_HARASSMENT_SEXUAL_CONTENT,
    PRIVACY_DOXXING,
    IMPERSONATION_DECEPTION,
    SPAM_COMMUNICATION_ABUSE,
    SCAMS_FRAUD_PHISHING,
    CHEATING_EXPLOITS_UNFAIR_PLAY,
    ILLEGAL_DANGEROUS_ACTIVITY,
    ACCOUNT_PLATFORM_ABUSE,
    INAPPROPRIATE_EXPLICIT_CONTENT,
    OTHER_PLATFORM_SPECIFIC
}
